version: '3.9'
services:
  kong:
    image: kong:3.6
    restart: unless-stopped
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_LOG_LEVEL: ${KONG_LOG_LEVEL:-notice}
      KONG_PROXY_LISTEN: '0.0.0.0:8000'
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
    volumes:
      - ./kong/kong.yml:/kong/kong.yml:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kong.rule=Host(`api.${DOMAIN}`)'
      - 'traefik.http.routers.kong.entrypoints=websecure'
      - 'traefik.http.routers.kong.tls.certresolver=letsencrypt'
      - 'traefik.http.services.kong.loadbalancer.server.port=8000'
