name: CI
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip pytest requests dnspython

      - name: Recommendations checker
        run: |
          . .venv/bin/activate
          python tools/check_recommendations.py || true

      - name: Run pytests
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          EXPECTED_IPV4: ${{ secrets.EXPECTED_IPV4 }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
        run: |
          . .venv/bin/activate
          pytest -q
