# Static Traefik configuration (complements CLI flags)
api:
  dashboard: true

accessLog: {}

log:
  level: INFO

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: cf
        domains:
          - main: ${BASE_DOMAIN}
            sans:
              - "*.${BASE_DOMAIN}"

certificatesResolvers:
  cf:
    acme:
      email: ${ACME_EMAIL}
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53
